### ISSUE TITLE
loading brigade.json fails in non-root container

### ISSUE THREAD

**Issue by joshgav** [brigadecore/brigade#1107]
The prestart.js script in the worker which preloads dependencies includes logic which copies the original `brigade.json` file to `/brigade.json` [here](https://github.com/brigadecore/brigade/blob/master/brigade-worker/prestart.js#L5). This fails in containers which cannot write to `/` and leads to the following error. Could you consider copying these files to a world-writable location like `/tmp` instead, or perhaps to something known to be writable like `/vcs`? Thanks.

NB: I included in the following output some messages about yarn caches too as FYI; that's another (small) issue which comes up in non-root containers.

```
warning Skipping preferred cache folder "/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1070090000".                
warning Cannot find a suitable global folder. Tried these: "/usr/local, /.yarn"
internal/fs/utils.js:230                                                                                           
    throw err;                                                                                                     
    ^                                                    
                                                         
Error: EACCES: permission denied, open '/brigade.json'                                                             
    at Object.openSync (fs.js:458:3)                                                                               
    at Object.writeFileSync (fs.js:1283:35)                                                                        
    at createConfig (/home/src/prestart.js:34:10)                                                                  
    at addDeps (/home/src/prestart.js:45:3)                                                                        
    at Object.<anonymous> (/home/src/prestart.js:41:3)                                                             
    at Module._compile (internal/modules/cjs/loader.js:1156:30)                                                    
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)                                      
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  errno: -13,                                            
  syscall: 'open',                                       
  code: 'EACCES',                                        
  path: '/brigade.json'                                  
} 
```

Output of `brig version`:

Latest version as of creation of this issue via `go get -u github.com/brigadecore/brigade/brig/cmd/brig`

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:57:29Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"a3ec9df", GitTreeState:"clean", BuildDate:"2020-05-04T12:54:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

OpenShift on EC2

**Comment by vdice** [comment]
Thanks for the issue.  I definitely think it's worth exploring moving the brigade.json into a world-writable location to support non-root containers (perhaps `/tmp/` as suggested).

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
