### ISSUE TITLE
Fix Windows Logger Agent build

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1345]
The Windows logger agent build has been failing.  See for example: https://github.com/brigadecore/brigade/pull/1344/checks?check_run_id=2282294495

Relevant output:

```
Invoking msys2 shell command: -defterm -no-start -c "ps -ef | grep '[?]' | awk '{print $2}' | xargs -r kill"
mkdir: cannot change permissions of '/dev/shm': Permission denied
mkdir: cannot change permissions of '/dev/mqueue': Permission denied
'C:\Windows\system32\drivers\etc\hosts' -> '/etc/hosts'
'C:\Windows\system32\drivers\etc\protocol' -> '/etc/protocols'
'C:\Windows\system32\drivers\etc\services' -> '/etc/services'
'C:\Windows\system32\drivers\etc\networks' -> '/etc/networks'
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
gpg: starting migration from earlier GnuPG versions
gpg: porting secret keys from '/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
gpg: migration succeeded
gpg: Generating pacman keyring master key...
gpg: key 650139CB43ABD93A marked as ultimately trusted
gpg: directory '/etc/pacman.d/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/888CD8F9848346FDE21E6470650139CB43ABD93A.rev'
gpg: Done
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
==> Appending keys from msys2.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key 123D4D51A1793859C2BE916BBBE514E53E0D0813...
  -> Locally signing key B91BCF3303284BF90CC043CA9F418C233E652008...
  -> Locally signing key 6E8FEAFF9644F54EED90EEA0790AE56A1D3CFDDC...
  -> Locally signing key 69985C5EB351011C78DF7F6D755B8182ACD22879...
  -> Locally signing key 9DD0D4217D75A33B896159E6DA7EF2ABAEEA755C...
  -> Locally signing key D55E7A6D7CE9BA1587C0ACACF40D263ECA25678A...
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
==> Disabling revoked keys in keyring...
  -> Disabling key B19514FB53EB3668471B296E794DCF97F93FC717...
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   6  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   6  signed:   6  trust: 0-, 0q, 0n, 6m, 0f, 0u
gpg: depth: 2  valid:   6  signed:   0  trust: 6-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2022-01-23
gpg: refreshing 13 keys from hkps://hkps.pool.sks-keyservers.net
gpg: key 794DCF97F93FC717: "Martell Malone (martell) <me@martellmalone.com>" not changed
gpg: key FA11531AA0AA7F57: "Christoph Reiter (MSYS2 development key) <reiter.christoph@gmail.com>" not changed
gpg: key 4DF3B7664CA56930: "Ray Donnelly (MSYS2 Developer) <mingw.android@gmail.com>" not changed
gpg: key D595C9AB2C51581E: "Martell Malone (MSYS2 Developer) <martellmalone@gmail.com>" not changed
gpg: key 974C8BE49078F532: "David Macek <david.macek.0@gmail.com>" not changed
gpg: key 5F92EFC1A47D45A1: "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" not changed
gpg: key 9F418C233E652008: "Ignacio Casal Quinteiro <icquinteiro@gmail.com>" not changed
gpg: key 755B8182ACD22879: "Christoph Reiter (MSYS2 master key) <reiter.christoph@gmail.com>" not changed
gpg: key BBE514E53E0D0813: "Ray Donnelly (MSYS2 Developer - master key) <mingw.android@gmail.com>" not changed
gpg: key DA7EF2ABAEEA755C: "Martell Malone (martell) <martellmalone@gmail.com>" not changed
gpg: key 790AE56A1D3CFDDC: "David Macek (MSYS2 master key) <david.macek.0@gmail.com>" not changed
gpg: key F40D263ECA25678A: "Alexey Pavlov (Alexpux) <alexey.pawlow@gmail.com>" not changed
gpg: Total number processed: 12
gpg:              unchanged: 12


###################################################################
#                                                                 #
#                                                                 #
#                   C   A   U   T   I   O   N                     #
#                                                                 #
#                  This is first start of MSYS2.                  #
#       You MUST restart shell to apply necessary actions.        #
#                                                                 #
#                                                                 #
###################################################################


kill: 275: No such process
kill: 276: No such process
kill: 274: No such process
Skipping updates due to the 'NoUpdate' option
 The install of msys2 was successful.
  Software installed to 'C:\ruby26\msys64'

Chocolatey installed 1/1 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Removing intermediate container 5889e049563b
 ---> b66bba3076b8
Step 5/7 : RUN ridk install 2 3   && echo gem: --no-document >> C:\ProgramData\gemrc   && gem install cool.io -v 1.5.4 --platform ruby   && gem install oj -v 3.3.10   && gem install json -v 2.2.0   && gem install fluentd -v 1.7.4   && gem install win32-service -v 1.0.1   && gem install win32-ipc -v 0.7.0   && gem install win32-event -v 0.6.3   && gem install windows-pr -v 1.2.6   && gem install bson -v 4.5.0   && gem install fluent-plugin-rewrite-tag-filter -v 2.3.0   && gem install fluent-plugin-mongo -v 1.4.1   && gem install fluent-plugin-kubernetes_metadata_filter -v 2.5.2   && gem install fluent-plugin-multi-format-parser -v 1.0.0   && gem sources --clear-all
 ---> Running in 046cb96c0551
> sh -lc true
MSYS2 seems to be properly installed
Remove catgets to avoid conflicts while update  ...
> pacman -Rdd catgets libcatgets --noconfirm
error: target not found: catgets
error: target not found: libcatgets
MSYS2 system update (optional) part 1  ...
> pacman -Syu --needed --noconfirm
:: Synchronizing package databases...
downloading mingw32.db...
downloading mingw32.db.sig...
downloading mingw64.db...
downloading mingw64.db.sig...
downloading msys.db...
downloading msys.db.sig...
:: Starting core system upgrade...
warning: terminate other MSYS2 programs before proceeding
resolving dependencies...
looking for conflicting packages...

Packages (5) filesystem-2021.03-6  mintty-1~3.4.7-2  msys2-runtime-3.2.0-3  pacman-5.2.2-18  pacman-mirrors-20210325-1

Total Download Size:    9.33 MiB
Total Installed Size:  44.49 MiB
Net Upgrade Size:       1.29 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
downloading filesystem-2021.03-6-x86_64.pkg.tar.zst...
downloading mintty-1~3.4.7-2-x86_64.pkg.tar.zst...
downloading msys2-runtime-3.2.0-3-x86_64.pkg.tar.zst...
downloading pacman-mirrors-20210325-1-any.pkg.tar.zst...
downloading pacman-5.2.2-18-x86_64.pkg.tar.zst...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
upgrading filesystem...
upgrading mintty...
upgrading msys2-runtime...
upgrading pacman-mirrors...
upgrading pacman...
:: To complete this update all MSYS2 processes including this terminal will be closed. Confirm to proceed [Y/n] 
MSYS2 system update (optional) succeeded
MSYS2 system update (optional) part 2 ...
> pacman -Su --needed --noconfirm
warning: database file for 'ucrt64' does not exist (use '-Sy' to download)
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
error: failed to prepare transaction (could not find database)
MSYS2 system update (optional) failed
C:/ruby26/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime/components/02_pacman_update.rb:29:in `block in execute': pacman failed (RuntimeError)
	from C:/ruby26/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime/msys2_installation.rb:197:in `with_msys_apps_enabled'
	from C:/ruby26/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime/components/02_pacman_update.rb:14:in `execute'
	from C:/ruby26/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
	from C:/ruby26/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
	from C:/ruby26/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
	from C:/ruby26/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
	from C:/ruby26/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
	from C:/ruby26/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
	from C:/ruby26/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
	from C:/ruby26/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
	from C:/ruby26/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
	from C:/ruby26/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
	from C:/ruby26/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime/components_installer.rb:34:in `install'
	from C:/ruby26/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime/ridk.rb:99:in `install'
	from C:/ruby26/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime/ridk.rb:14:in `run!'
	from C:/ruby26/bin/ridk.cmd:39:in `<main>'
 _____       _           _____           _        _ _         ___  
|  __ \     | |         |_   _|         | |      | | |       |__ \ 
| |__) |   _| |__  _   _  | |  _ __  ___| |_ __ _| | | ___ _ __ ) |
|  _  / | | | '_ \| | | | | | | '_ \/ __| __/ _` | | |/ _ \ '__/ / 
| | \ \ |_| | |_) | |_| |_| |_| | | \__ \ || (_| | | |  __/ | / /_ 
|_|  \_\__,_|_.__/ \__, |_____|_| |_|___/\__\__,_|_|_|\___|_||____|
                    __/ |           _                              
                   |___/          _|_ _  __   | | o __  _| _     _ 
                                   | (_) |    |^| | | |(_|(_)\^/_> 

The command 'cmd /S /C ridk install 2 3   && echo gem: --no-document >> C:\ProgramData\gemrc   && gem install cool.io -v 1.5.4 --platform ruby   && gem install oj -v 3.3.10   && gem install json -v 2.2.0   && gem install fluentd -v 1.7.4   && gem install win32-service -v 1.0.1   && gem install win32-ipc -v 0.7.0   && gem install win32-event -v 0.6.3   && gem install windows-pr -v 1.2.6   && gem install bson -v 4.5.0   && gem install fluent-plugin-rewrite-tag-filter -v 2.3.0   && gem install fluent-plugin-mongo -v 1.4.1   && gem install fluent-plugin-kubernetes_metadata_filter -v 2.5.2   && gem install fluent-plugin-multi-format-parser -v 1.0.0   && gem sources --clear-all' returned a non-zero code: 1
Error: Process completed with exit code 1.
```

Here is the Windows agent Dockerfile: https://github.com/brigadecore/brigade/blob/v2/v2/logger/Dockerfile.winserv-2019

and GH action yaml: https://github.com/brigadecore/brigade/blob/v2/.github/workflows/pr.yaml

**Comment by vdice** [comment]
Fixed by https://github.com/brigadecore/brigade/pull/1360
