### ISSUE TITLE
Bug: Module @brigadecore/brigadier has no exported member Group

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1415]
Looks like the worker image's brigadier polyfill does not export `Group`.

I have a vague recollection of touching something recently that _might_ have messed up some exports, so this is almost certainly my doing. I'll fix.

```
$ bin/brig-darwin-amd64 event logs -i a204bd36-9e5f-4efa-8da6-842015372355 -f

2021-05-25T00:45:33.322Z INFO: brigade-worker version: 0c5f310
2021-05-25T00:45:33.324Z DEBUG: using yarn as the package manager
2021-05-25T00:45:33.324Z DEBUG: found a package.json at /var/vcs/.brigade/package.json
2021-05-25T00:45:33.325Z DEBUG: installing dependencies using yarn
warning package.json: No license field
warning brigade-ci-cd: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
2021-05-25T00:45:34.862Z DEBUG: path /var/vcs/.brigade/node_modules/@brigadecore/brigadier exists; deleting it
2021-05-25T00:45:34.865Z DEBUG: polyfilling @brigadecore/brigadier with /var/brigade-worker/brigadier-polyfill
2021-05-25T00:45:34.865Z DEBUG: compiling brigade.ts with flags --target ES6 --module commonjs --esModuleInterop
brigade.ts(1,23): error TS2305: Module '"@brigadecore/brigadier"' has no exported member 'Group'.
/var/brigade-worker/worker/dist/prestart.js:153
        throw new Error(`error compiling brigade.ts:\n\n${e.output}`);
        ^

Error: error compiling brigade.ts:

,,
    at defaultCompile (/var/brigade-worker/worker/dist/prestart.js:153:15)
    at Object.<anonymous> (/var/brigade-worker/worker/dist/prestart.js:82:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by krancour** [comment]
Whoops. I forgot that Group was replaced with `ConcurrentGroup` and `SerialGroup` which allow for composing jobs in an arbitrarily complex manner.

I updated my script accordingly.

There's actually no issue here.
